export default {
    OPEN_SUBJECT_MODAL:'OPEN_SUBJECT_MODAL',
    CLOSE_SUBJECT_MODAL:'CLOSE_SUBJECT_MODAL',
    OPEN_LESSON_MODAL:'OPEN_LESSON_MODAL',
    CLOSE_LESSON_MODAL:'CLOSE_LESSON_MODAL',
    SIGNUP_USER:'SIGNUP_USER',
    LOGIN_USER:'LOGIN_USER',
    LOGOUT_USER:'LOGOUT_USER',
}