export default {
    OPEN_SUBJECT_MODAL: "OPEN_SUBJECT_MODAL",
    CLOSE_SUBJECT_MODAL: "CLOSE_SUBJECT_MODAL",
    OPEN_LESSON_MODAL: "OPEN_LESSON_MODAL",
    CLOSE_LESSON_MODAL: "CLOSE_LESSON_MODAL",
    LOGIN_USER: "LOGIN_USER",
    SET_USER: "SET_USER",
    SET_TOKEN:"SET_TOKEN",
    LOGOUT_USER: "LOGOUT_USER",
};
